### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by MarkSwanson** [rozaliev/mirage#1]
I'm using the stated version:

$ rustc --version
rustc 1.25.0-nightly (a0dcecff9 2018-01-24)

However, I get build errors:

error[E0277]: the trait bound `quote::__rt::TokenTree: std::convert::From<proc_macro2::TokenTree>` is not satisfied
   --> /home/me/.cargo/git/checkouts/syn-6f4912dca572d3ab/d5e9859/synom/src/tokens.rs:312:20
    |
312 |             tokens.append(TokenTree {
    |                    ^^^^^^ the trait `std::convert::From<proc_macro2::TokenTree>` is not implemented for `quote::__rt::TokenTree`
    |
    = help: the following implementations were found:
              <quote::__rt::TokenTree as std::convert::From<quote::__rt::TokenNode>>
    = note: required because of the requirements on the impl of `std::convert::Into<quote::__rt::TokenTree>` for `proc_macro2::TokenTree`

It might be useful to be more strict when specifying dependency semver versions...

**Comment by rozaliev** [comment]
Should be fixed on master now, thanks for the report.
